# Generated by Django 2.1 on 2019-04-17 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None)),
                ('website', models.TextField(default='')),
                ('yelp', models.TextField(default='')),
                ('youtube', models.TextField(default='')),
                ('facebook', models.TextField(default='')),
                ('twitter', models.TextField(default='')),
                ('email', models.TextField(default='')),
            ],
            options={
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='CategoryQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_quantities', to='finder.Business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('name', models.TextField(blank=True, default='')),
                ('location_heading', models.TextField(default='')),
                ('street1', models.TextField(default='')),
                ('street2', models.TextField(default='')),
                ('city', models.TextField(default='')),
                ('state_code', models.CharField(max_length=2, null=True)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=11, null=True)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='finder.Business')),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='StoreLogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
                ('log_item_type', models.IntegerField(blank=True, default=None)),
                ('timestamp', models.DateTimeField(blank=True, default=None)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_items', to='finder.Store')),
            ],
            options={
                'db_table': 'store_log_item',
            },
        ),
    ]
